include:
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-dom0.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-vm.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.2/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.2/gitlab-host.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.2/gitlab-vm.yml'

checks:pylint:
  before_script:
  - sudo dnf install -y python3-gobject gtk3 python3-pylint python3-pydbus
  script:
  - python3 -m pylint --rcfile=.pylintrc disk_password_gui
  stage: checks

checks:mypy:
  before_script:
  - sudo dnf install -y python3-mypy python3-pydbus
  script:
  - mypy --install-types --non-interactive disk_password_gui
  stage: checks

checks:tests:
  before_script:
  - sudo dnf install -y python3-gobject gtk3 python3-pydbus python3-pytest xdotool xorg-x11-server-Xvfb
  script:
  - xvfb-run pytest -v disk_password_gui
  stage: checks
