#!/bin/sh

set -xe
dev=/dev/xvdc3
pass=abc
echo -n $pass | cryptsetup luksFormat $dev -
echo -n $pass | cryptsetup open --key-file=- $dev luks
vgcreate -f qubes_test /dev/mapper/luks
lvcreate -V 500M -l 100%FREE -n root --thin-pool root-pool qubes_test
mkfs.ext4 -F /dev/qubes_test/root
mount /dev/qubes_test/root /mnt
